<?php
use Illuminate\Database\Seeder;

class Default_009_TownshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('townships')->delete();
        $today = date('Y-m-d H:i:s');
        
        $objs = array(
            ['city_id'=>'4', 'name'=>'Myitkyina', 'id' =>'1', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Bhamo (Bamaw)', 'id' =>'2', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Bharma', 'id' =>'3', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Chipwi (Chibwe)', 'id' =>'4', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Hpakant (Hpakan, Farkent)', 'id' =>'5', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Hopin (Hobik)', 'id' =>'6', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Hsinbo (Sinbo)', 'id' =>'7', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Hsawlaw (Sawlaw)', 'id' =>'8', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Injangyang', 'id' =>'9', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Kamaing (Kamine)', 'id' =>'10', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Kawnglanghpu (Kaunglanfu)', 'id' =>'11', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Lweje (Loije, Lwalgyai)', 'id' =>'12', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Machanbaw', 'id' =>'13', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Mansi', 'id' =>'14', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Momauk', 'id' =>'15', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Moekaung', 'id' =>'16', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Mohnyin', 'id' =>'17', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Nogmung (Naungmoon)', 'id' =>'18', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Pannandin', 'id' =>'19', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Putao', 'id' =>'20', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Shwegu', 'id' =>'21', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Sumprabum', 'id' =>'22', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Tanai (Tanain)', 'id' =>'23', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Tsawlaw (Sawlaw)', 'id' =>'24', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Waingmaw', 'id' =>'25', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'4', 'name'=>'Ywathit', 'id' =>'26', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'5', 'name'=>'Loikaw', 'id' =>'27', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'5', 'name'=>'Demawso', 'id' =>'28', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'5', 'name'=>'Pruhso', 'id' =>'29', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'5', 'name'=>'Shadaw', 'id' =>'30', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'5', 'name'=>'Bawlakhe', 'id' =>'31', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'5', 'name'=>'Hpasawng', 'id' =>'32', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'5', 'name'=>'Maisal', 'id' =>'33', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Hpa-an', 'id' =>'34', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Hlaingbwe (Hlinebwe)', 'id' =>'35', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Papun (Phapun)', 'id' =>'36', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Thandang', 'id' =>'37', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Thandanggyi (Thantaunggyi)', 'id' =>'38', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Myawaddy (Myawadi)', 'id' =>'39', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Kawkareik (Kawkareit)', 'id' =>'40', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Kyeikdon', 'id' =>'41', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Kyain Seikgyi (Kyainseikkyi)', 'id' =>'42', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'6', 'name'=>'Payathonsu (Hpayarthonesu)', 'id' =>'43', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Tedim', 'id' =>'44', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Tonzang', 'id' =>'45', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Falam (Phalam)', 'id' =>'46', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Hakha (Haka, Harkhar)', 'id' =>'47', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Thantlang (Htantlang)', 'id' =>'48', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Kanpetlet (Kanpatlat)', 'id' =>'49', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Matupi (Matupe)', 'id' =>'50', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Mindat (Minthet)', 'id' =>'51', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Paletwa', 'id' =>'52', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Cikha', 'id' =>'53', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Rih Khawdar', 'id' =>'54', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Razua (Yay Zwar)', 'id' =>'55', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'3', 'name'=>'Sami (Samee)', 'id' =>'56', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Mawlamyaing(Moulmein)', 'id' =>'57', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Bilin', 'id' =>'58', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Kyaikmaraw', 'id' =>'59', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Chaungzon', 'id' =>'60', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Thanbyuzayat', 'id' =>'61', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Kyaikkami', 'id' =>'62', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Mudon', 'id' =>'63', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Ye', 'id' =>'64', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Thaton', 'id' =>'65', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Paung', 'id' =>'66', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Kyaikto', 'id' =>'67', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'9', 'name'=>'Mottama', 'id' =>'68', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Sittwe', 'id' =>'69', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Ann', 'id' =>'70', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Buthidaung', 'id' =>'71', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Dalet (Dalat)', 'id' =>'72', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Gwa', 'id' =>'73', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Kyaukpyu', 'id' =>'74', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Kyauktaw', 'id' =>'75', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Kyeintali', 'id' =>'76', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Manaung', 'id' =>'77', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Maungdaw', 'id' =>'78', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Minbya', 'id' =>'79', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Mrauk U', 'id' =>'80', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Myebon', 'id' =>'81', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Ngapali', 'id' =>'82', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Pauktaw', 'id' =>'83', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Ponnagyun', 'id' =>'84', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Ramree', 'id' =>'85', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Rathedaung', 'id' =>'86', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Thandwe', 'id' =>'87', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'10', 'name'=>'Toungup', 'id' =>'88', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Toungup', 'id' =>'89', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Aungban', 'id' =>'90', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Toungup', 'id' =>'91', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Ayetharyar', 'id' =>'92', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Chinshwehaw', 'id' =>'93', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Ho-pin', 'id' =>'94', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Hopang', 'id' =>'95', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Hopong', 'id' =>'96', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Hseni', 'id' =>'97', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Hsi Hseng', 'id' =>'98', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Hsipaw', 'id' =>'99', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Kalaw', 'id' =>'100', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Kengtong', 'id' =>'101', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Kunhing', 'id' =>'102', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Kunlong', 'id' =>'103', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Kutkai', 'id' =>'104', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Kyaukme', 'id' =>'105', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Kyethi', 'id' =>'106', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Lai-Hka', 'id' =>'107', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Langkho', 'id' =>'108', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Lashio', 'id' =>'109', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Lawksawk', 'id' =>'110', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Loilen', 'id' =>'111', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Laukkaing', 'id' =>'112', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mabein', 'id' =>'113', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mantong', 'id' =>'114', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mawkmai', 'id' =>'115', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Hsu', 'id' =>'116', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Khet', 'id' =>'117', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Kung', 'id' =>'118', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Nai', 'id' =>'119', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Pan', 'id' =>'120', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Ping', 'id' =>'121', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Tong', 'id' =>'122', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Yang', 'id' =>'123', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Yawng', 'id' =>'124', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mine Hsat', 'id' =>'125', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mineko', 'id' =>'126', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Minemit', 'id' =>'127', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mineyai', 'id' =>'128', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Mu Se', 'id' =>'129', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Namhsan', 'id' =>'130', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Namtu', 'id' =>'131', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Nanhkan', 'id' =>'132', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Nansang', 'id' =>'133', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Nawnghkio', 'id' =>'134', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Nyaungshwe', 'id' =>'135', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Pang Long', 'id' =>'136', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Pekon', 'id' =>'137', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Pindaya', 'id' =>'138', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Pinlaung', 'id' =>'139', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Tant Yan', 'id' =>'140', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Taunggyi', 'id' =>'141', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Techilelk', 'id' =>'142', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'12', 'name'=>'Ywangan', 'id' =>'143', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Ayadaw', 'id' =>'144', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Banmauk', 'id' =>'145', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Budalin', 'id' =>'146', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Chaung', 'id' =>'147', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Dabayin', 'id' =>'148', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Hkamti', 'id' =>'149', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Homalin', 'id' =>'150', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Htigyaing', 'id' =>'151', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Indaw', 'id' =>'152', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Kalaymyo', 'id' =>'153', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Kalewa', 'id' =>'154', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Kanbalu', 'id' =>'155', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Kani', 'id' =>'156', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Katha', 'id' =>'157', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Kawlin', 'id' =>'158', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Khin U', 'id' =>'159', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Kyadet', 'id' =>'160', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Kyunhla', 'id' =>'161', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Mawlaik', 'id' =>'162', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Mingun', 'id' =>'163', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Monywa', 'id' =>'164', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Myaung', 'id' =>'165', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Myinmu', 'id' =>'166', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Pale', 'id' =>'167', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Paungbyin', 'id' =>'168', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Pinlebu', 'id' =>'169', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Sagaing', 'id' =>'170', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Salingyi', 'id' =>'171', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Shwebo', 'id' =>'172', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Tamu', 'id' =>'173', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Tantsal', 'id' =>'174', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Wetlet', 'id' =>'175', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Wuntho', 'id' =>'176', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Ye-U', 'id' =>'177', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Yinmabin', 'id' =>'178', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'11', 'name'=>'Mungnii', 'id' =>'179', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Dawei', 'id' =>'180', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Launglon', 'id' =>'181', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Thayetchaung', 'id' =>'182', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Yebyu', 'id' =>'183', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Myeik', 'id' =>'184', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Kyunsu', 'id' =>'185', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Palaw', 'id' =>'186', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Taninthayi', 'id' =>'187', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Kawthoung', 'id' =>'188', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'13', 'name'=>'Bokpyin', 'id' =>'189', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Bago', 'id' =>'190', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Thanatpin', 'id' =>'191', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Kawa', 'id' =>'192', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Waw', 'id' =>'193', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Nyaunglebin', 'id' =>'194', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Madauk', 'id' =>'195', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Pyuntaza', 'id' =>'196', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Kyauktaga', 'id' =>'197', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Pennwegone', 'id' =>'198', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Daik-U', 'id' =>'199', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Shwegyin', 'id' =>'200', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Taungoo', 'id' =>'201', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Kututmatyi', 'id' =>'202', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Yaytarshay', 'id' =>'203', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Kyaukkyi', 'id' =>'204', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Phyu', 'id' =>'205', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Oktwin', 'id' =>'206', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Htantabin', 'id' =>'207', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Pyay', 'id' =>'208', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Paukkhaung', 'id' =>'209', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Padaung', 'id' =>'210', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Paungde', 'id' =>'211', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Thegon', 'id' =>'212', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Shwedaung', 'id' =>'213', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Thayarwaddy', 'id' =>'214', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Thonze', 'id' =>'215', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Letpadan', 'id' =>'216', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Minhla', 'id' =>'217', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Okpo', 'id' =>'218', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Zigon', 'id' =>'219', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Nattalin', 'id' =>'220', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Monyo', 'id' =>'221', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'2', 'name'=>'Gyobingauk', 'id' =>'222', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Magwe', 'id' =>'223', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Allanmyo (Aunglan, Myaydo)', 'id' =>'224', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Chauck', 'id' =>'225', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Gangaw', 'id' =>'226', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Kamma', 'id' =>'227', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Minbu', 'id' =>'228', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Mindon', 'id' =>'229', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Minhla', 'id' =>'230', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Myaing', 'id' =>'231', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Myothit', 'id' =>'232', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Natmauk', 'id' =>'233', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Ngape', 'id' =>'234', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Pakokku', 'id' =>'235', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Pauk', 'id' =>'236', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Pwintbyu', 'id' =>'237', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Sagu', 'id' =>'238', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Salin', 'id' =>'239', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Swar', 'id' =>'240', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Seikphyu', 'id' =>'241', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Sidoktaya', 'id' =>'242', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Sinbyugyun', 'id' =>'243', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Taungdwingyi', 'id' =>'244', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Thayet', 'id' =>'245', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Tilin', 'id' =>'246', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'7', 'name'=>'Yenangyaung', 'id' =>'247', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>' Ahlon', 'id' =>'248', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>' Bahan', 'id' =>'249', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Botataung', 'id' =>'250', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Cocokyun', 'id' =>'251', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Dagon', 'id' =>'252', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Dagon Myothit(East)', 'id' =>'253', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Dagon Myothit(North)', 'id' =>'254', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Dagon Myothit(Seikkan)', 'id' =>'255', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Dagon Myothit(South)', 'id' =>'256', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Dala', 'id' =>'257', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Dawbon', 'id' =>'258', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Hlaing', 'id' =>'259', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Hlaingtharya', 'id' =>'260', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Hlegu', 'id' =>'261', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Hmawbi', 'id' =>'262', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Htantabin', 'id' =>'263', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Insein', 'id' =>'264', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Kamaryut', 'id' =>'265', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Kayan', 'id' =>'266', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Kawhmu', 'id' =>'267', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Kungyangon', 'id' =>'268', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Kyauktada', 'id' =>'269', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Kyauktan', 'id' =>'270', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Kyeemyindaing', 'id' =>'271', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Lanmadaw', 'id' =>'272', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Latha', 'id' =>'273', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Mayangone', 'id' =>'274', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Mingaladon', 'id' =>'275', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Mingalartaungnyunt', 'id' =>'276', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'North Okkalapa', 'id' =>'277', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Pabedan', 'id' =>'278', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Pazundaung', 'id' =>'279', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Sanchaung', 'id' =>'280', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Seikgyikanaungto', 'id' =>'281', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Seikkan', 'id' =>'282', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Shwepyithar', 'id' =>'283', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'South Okkalapa', 'id' =>'284', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Taikkyi', 'id' =>'285', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Tamwe', 'id' =>'286', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Thaketa', 'id' =>'287', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Thanlyin', 'id' =>'288', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Thingangkuun', 'id' =>'289', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Thongwa', 'id' =>'290', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Twantay', 'id' =>'291', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'14', 'name'=>'Yankin', 'id' =>'292', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Pathein', 'id' =>'293', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Kangyidaut', 'id' =>'294', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Thabaung', 'id' =>'295', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Ngapudaw', 'id' =>'296', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Haigyi Island', 'id' =>'297', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Kyonpyaw', 'id' =>'298', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Yekyi', 'id' =>'299', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Kyaunggon', 'id' =>'300', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Hinthada', 'id' =>'301', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Zalun', 'id' =>'302', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Lemyethna', 'id' =>'303', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Myan Aung', 'id' =>'304', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Kanaung', 'id' =>'305', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Kyangin', 'id' =>'306', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Ingapu', 'id' =>'307', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Myaungmya', 'id' =>'308', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Einme', 'id' =>'309', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Letputta', 'id' =>'310', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Wakema', 'id' =>'311', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Mawlamyinegyun', 'id' =>'312', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Maubin', 'id' =>'313', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Pantanaw', 'id' =>'314', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Nyaungdon', 'id' =>'315', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Danubyu', 'id' =>'316', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Pyapon', 'id' =>'317', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Bogale', 'id' =>'318', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Kyaiklat', 'id' =>'319', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'1', 'name'=>'Dedaye', 'id' =>'320', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Amarapura', 'id' =>'321', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Aungmyaythazan', 'id' =>'322', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Chanayethazan', 'id' =>'323', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Chanmyathazi', 'id' =>'324', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Kyaukpadaung', 'id' =>'325', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Kyaukse', 'id' =>'326', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Lewe', 'id' =>'327', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Madaya', 'id' =>'328', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Mahaaungmyay', 'id' =>'329', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Mahlaing', 'id' =>'330', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Meiktila', 'id' =>'331', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Mogoke', 'id' =>'332', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Myingyan', 'id' =>'333', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Myittha', 'id' =>'334', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Natogyi', 'id' =>'335', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Ngazun', 'id' =>'336', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Nyaung-U', 'id' =>'337', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Patheingyi', 'id' =>'338', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Pyawbwe', 'id' =>'339', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Pyigyitagon', 'id' =>'340', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Pyinmana', 'id' =>'341', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Pyinoolwin', 'id' =>'342', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Singu', 'id' =>'343', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Sintgaing', 'id' =>'344', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Sintgaing', 'id' =>'345', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Tada-U', 'id' =>'346', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Tatkon', 'id' =>'347', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Taungtha', 'id' =>'348', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Thabeikkyin', 'id' =>'349', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Thazi', 'id' =>'350', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Wundwin', 'id' =>'351', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Yamethin', 'id' =>'352', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'15', 'name'=>'Pyinmana', 'id' =>'353', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'15', 'name'=>'Tatkon', 'id' =>'354', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'15', 'name'=>'Lewe', 'id' =>'355', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'15', 'name'=>'Ottarathiri', 'id' =>'356', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'15', 'name'=>'Dekkhinathiri', 'id' =>'357', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'15', 'name'=>'Pobbathiri', 'id' =>'358', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'15', 'name'=>'Zabuthiri', 'id' =>'359', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'15', 'name'=>'Zeyathiri', 'id' =>'360', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Bagan', 'id' =>'361', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'Old Bagan', 'id' =>'362', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
            ['city_id'=>'8', 'name'=>'New Bagan', 'id' =>'363', 'created_by' =>'1', 'updated_by' =>'1','created_by'=>1,'created_at'=>$today],
        );
        DB::table('townships')->insert($objs);
    }
}