@include('layouts_frontend.partial_frontend.header_frontend')
@yield('script')
@yield('page_script')
@yield('content')
@include('layouts_frontend.partial_frontend.footer_frontend')
@include('sweet::alert')
